
from securewei.solc_parsing.variables.variable_declaration import VariableDeclarationSolc
from securewei.core.variables.function_type_variable import FunctionTypeVariable

class FunctionTypeVariableSolc(VariableDeclarationSolc, FunctionTypeVariable): pass
